### ISSUE TITLE
Noisy docs

### ISSUE THREAD

**Issue by Stebalien** [ipld/go-ipld-adl-hamt#19]
Can we move the IPLD types to a sub-package? It's rather difficult to actually _find_ the functions for working with the HAMT, and I'm not sure I even have:

https://pkg.go.dev/github.com/ipld/go-ipld-adl-hamt

**Comment by Stebalien** [comment]
Actually... can I seriously not just put/get? This API is _really_ painful.

**Comment by Stebalien** [comment]
Closing because this is a much bigger issue.

**Comment by mvdan** [comment]
You should see https://github.com/ipld/go-ipld-adl-hamt/issues/17.
